micronaut:
  application:
    name: http-client-example
  http:
    client:
      read-idle-timeout: 500ms
      connect-timeout: 500ms

host:
  viacep: http://viacep.com.br

tracing:
  jaeger:
    enabled: true